### ISSUE TITLE
Remove error message string interpolation 

### ISSUE THREAD

**Issue by razor-x** [seamapi/python#62]
I don't think the error message should contain this interpolated data, but I need to run a few local tests to see how to best display the error 

```
f"SeamApiException: status={self.status_code}, request_id={self.request_id}, metadata={self.metadata}"
```

_Originally posted by @razor-x in https://github.com/seamapi/python-next/issues/48#issuecomment-2118217674_

**Comment by andrii-balitskyi** [comment]
@razor-x, I believe this was fixed by https://github.com/seamapi/python/pull/99. Or did you have something else in mind?
